# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Location',
            new_name='location',
        ),
    ]
