# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-26 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='artist',
        ),
    ]
