# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180326_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='play',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
