# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-29 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('cover', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='play',
        ),
    ]
