# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-30 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180329_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('cover', models.URLField()),
                ('song_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
