# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-20 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180315_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 20, 15, 30, 36, 120729, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='article.Tag'),
        ),
    ]
