# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-26 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20180326_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 13, 43, 11, 957145, tzinfo=utc)),
        ),
    ]
