# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-02 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20180402_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 14, 32, 58, 266908, tzinfo=utc)),
        ),
    ]
